<?php

declare(strict_types=1);

namespace Plugins\ComLogicommerceMagicfront\Dtos\Widgets;

use SDK\Core\Dtos\Traits\ElementTrait;

/**
 * This is the WidgetTemplateChildStructure class.
 * The information of API widget template child structure descriptors will be stored in that class and will remain immutable (only get methods are available)
 *
 * @see WidgetTemplateChildStructure::getId()
 * @see WidgetTemplateChildStructure::getStyles()
 *
 * @see ElementTrait
 *
 * @package Plugins\ComLogicommerceMagicfront\Core\Dtos
 */
class WidgetTemplateChildStructure {
    use ElementTrait;

    protected string $id = '';

    protected array $styles = [];

    /**
     * Returns the child structure id (UUID generated by the API).
     *
     * @return string
     */
    public function getId(): string {
        return $this->id;
    }

    /**
     * Returns the per-child style definitions.
     *
     * @return WidgetTemplateStyle[]
     */
    public function getStyles(): array {
        return $this->styles;
    }

    protected function setStyles(array $styles): void {
        $this->styles = $this->setArrayField($styles, WidgetTemplateStyle::class);
    }
}
