<?php

declare(strict_types=1);

namespace Plugins\ComLogicommerceMagicfront\Dtos\Widgets;

use SDK\Core\Dtos\Element;
use SDK\Core\Dtos\Traits\ElementTrait;

/**
 * This is the WidgetInstance class.
 * The information of API widget instances will be stored in that class and will remain immutable (only get methods are available)
 *
 * @see WidgetInstance::getId()
 * @see WidgetInstance::getParentId()
 * @see WidgetInstance::getWidgetTemplateId()
 * @see WidgetInstance::getType()
 * @see WidgetInstance::getOrderIndex()
 * @see WidgetInstance::getAutoGenerated()
 * @see WidgetInstance::getPropertyValues()
 * @see WidgetInstance::getStyleValues()
 * @see WidgetInstance::getChildren()
 *
 * @see Element
 * @see ElementTrait
 *
 * @package Plugins\ComLogicommerceMagicfront\Core\Dtos
 */
class WidgetInstance extends Element {
    use ElementTrait;

    protected string $id = '';

    protected ?string $parentId = null;

    protected string $widgetTemplateId = '';

    /**
     * Internal alias — mirrors `widgetTemplateId` when the API omits a separate
     * `type` field, so rendering code can always call getType() uniformly.
     */
    protected string $type = '';

    protected int $orderIndex = 0;

    protected ?bool $autoGenerated = null;

    /**
     * Id of the slot this widget fills, set only for children auto-created
     * from a template slot declaration. Null for user-added widgets and
     * childStructure pseudo-widgets.
     */
    protected ?string $slotId = null;

    /**
     * Permissions resolved server-side from the slot's declaration. Null
     * when slotId is null. Keys: allowMove, allowDelete, allowDuplicate,
     * allowTypeChange (all booleans).
     */
    protected ?array $slotPermissions = null;

    protected array $propertyValues = [];

    protected array $styleValues = [];

    protected array $children = [];

    /**
     * Returns the widget instance id.
     *
     * @return string
     */
    public function getId(): string {
        return $this->id;
    }

    /**
     * Returns the parent widget id, or NULL for top-level widgets.
     *
     * @return string|NULL
     */
    public function getParentId(): ?string {
        return $this->parentId;
    }

    /**
     * Returns the widget template id (UUID) this instance was created from.
     *
     * @return string
     */
    public function getWidgetTemplateId(): string {
        return $this->widgetTemplateId;
    }

    /**
     * Returns the widget type identifier. Mirrors widgetTemplateId unless the API
     * supplied a legacy `type` string.
     *
     * @return string
     */
    public function getType(): string {
        return $this->type;
    }

    /**
     * Returns the widget position within its parent container.
     *
     * @return int
     */
    public function getOrderIndex(): int {
        return $this->orderIndex;
    }

    /**
     * Returns TRUE if the widget was auto-generated (e.g. via childStructure), FALSE if
     * user-created, or NULL when the API did not report this flag.
     *
     * @return bool|NULL
     */
    public function getAutoGenerated(): ?bool {
        return $this->autoGenerated;
    }

    public function getSlotId(): ?string {
        return $this->slotId;
    }

    public function getSlotPermissions(): ?array {
        return $this->slotPermissions;
    }

    /**
     * Returns the raw property value entries for this instance.
     *
     * @return array
     */
    public function getPropertyValues(): array {
        return $this->propertyValues;
    }

    /**
     * Returns the raw style value entries for this instance.
     *
     * @return array
     */
    public function getStyleValues(): array {
        return $this->styleValues;
    }

    /**
     * Returns the child widget instances.
     *
     * @return array
     */
    public function getChildren(): array {
        return $this->children;
    }

    /**
     * When `widgetTemplateId` is set during hydration, also populate the `type`
     * alias so getType() returns a non-empty identifier even if the API did not
     * emit a separate legacy `type` field.
     */
    protected function setWidgetTemplateId(string $id): void {
        $this->widgetTemplateId = $id;
        if ($this->type === '') {
            $this->type = $id;
        }
    }

    protected function setChildren(array $children): void {
        $this->children = $this->setArrayField($children, self::class);
    }

    /**
     * Explicit setters are required because SDK's ElementTrait reflects on
     * `set<Field>` methods; protected fields alone are not populated from
     * the API payload. Without these, slotId/slotPermissions silently drop
     * during deserialization and slot-bound widgets can't be matched to
     * their {{ mff_widget_slot('id') }} placeholder at render time.
     */
    protected function setSlotId(?string $slotId): void {
        $this->slotId = $slotId;
    }

    protected function setSlotPermissions(?array $slotPermissions): void {
        $this->slotPermissions = $slotPermissions;
    }
}
